image: maven:latest

variables:
  MONGO_DB_NAME: "pfeDB"
  MONGO_DB_RECREATE: "false"
  MONGO_DB_URI: "mongodb+srv://pfeDBuser:pfeDBuser@cluster0-xu5x8.mongodb.net/test?retryWrites=true"
  ALGOLIA_APIKEY: "a9c365040478a758605bd53c994be222"
  ALGOLIA_APPID: "RB9XCJY8MF"

  MAVEN_CLI_OPTS: "-s .m2/settings.xml -B"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  
  DOCKER_DRIVER: overlay2
  
cache:
  paths:
    - .m2/repository/
    - .m2/settings.xml
    - target/
    
stages:
  - build
  - test
  - deploy
  - production


build:
  stage: build
  script:
    - mkdir -p .m2/
    - echo '<?xml version="1.0" encoding="UTF-8"?>
            <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
            </settings>' > .m2/settings.xml
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
    
check_style:
  stage: test
  script:
    - mvn clean checkstyle:check -B
  allow_failure: true

development:
  stage: deploy
  image: ruby:2.2
  only:
    - master
  script:
  - gem install dpl
  - dpl --provider=heroku --app=pfe-groupe1-backend --api-key=90421c5e-738e-4675-a999-a004853600b4

production:
  stage: production
  image: ruby:2.2
  only:
    - master
  script:
  - gem install dpl
  - dpl --provider=heroku --app=pfe1-backend --api-key=90421c5e-738e-4675-a999-a004853600b4
  when: manual

#include:
  #- template: Jobs/Build.gitlab-ci.yml
  #- template: Jobs/Test.gitlab-ci.yml

